include:
  remote: 'https://github.com/git-developer/docker-support/raw/develop/gitlab-ci/docker-support.yml'

stages:
  - prepare
  - build

Collect Metadata:
  extends: .docker_support:.collect_image_metadata
  stage: prepare

Build:
  extends: .docker_support:.build_image
  stage: build
  variables:
    BUILD_CONTEXT:   "image"
    IMAGE_PLATFORMS: "linux/amd64,linux/arm/v7"
