variables:
  BUILD_CONTEXT:      image
  IMAGE_PLATFORMS:    linux/amd64,linux/arm/v7

include:
  remote: "https://github.com/git-developer/docker-support/raw/v1.0.0/gitlab-ci/docker-support.yml"

Build Container Image:
  extends: .docker_support:.build_image
