variables:
  IMAGE_PLATFORMS:    linux/amd64,linux/i386,linux/arm/v7,linux/arm64/v8

include:
  remote: "https://github.com/git-developer/docker-support/raw/develop/gitlab-ci/docker-template.yml"

stages:
  - setup
  - prepare
  - analyze
  - publish

Collect Additional Tags:
  extends: .docker_support:.with_bare_image
  stage: analyze
  dependencies:
  - Collect Tags
  - Build Image
  artifacts:
    paths:
    - tags
  script:
  - echo >tags/demo "${IMAGE_NAME}:demo"
  - echo >tags/version "${IMAGE_NAME}:busybox-$(docker run --rm "${IMAGE_NAME}:${BUILD_CACHE}" sh -c 'busybox | head -1 | cut -d " " -f 2')"
  - echo GITLAB_USER_EMAIL=$GITLAB_USER_EMAIL
  - echo GITLAB_USER_ID=$GITLAB_USER_ID
  - echo GITLAB_USER_LOGIN=$GITLAB_USER_LOGIN
  - echo GITLAB_USER_NAME=$GITLAB_USER_NAME
