variables:
  BUILD_CONTEXT:      image
  IMAGE_PLATFORMS:    linux/amd64,linux/i386,linux/arm/v7,linux/arm64/v8

include:
  remote: "https://github.com/git-developer/docker-support/raw/develop/gitlab-ci/docker-support.yml"

stages:
  - prepare
  - analyze
  - build

Collect Tags:
  extends: .docker_support:.collect_tags
  stage: prepare

Collect Labels:
  extends: .docker_support:.collect_labels
  stage: prepare

Build Image:
  extends: .docker_support:.build_bare_image
  stage: prepare

Collect Additional Tags:
  extends: .docker_support:.with_bare_image
  stage: analyze
  dependencies:
  - Collect Tags
  - Build Image
  artifacts:
    paths:
    - tags
  script:
  - echo >tags/demo "${CI_PROJECT_PATH}:demo"
  - echo >tags/version "${CI_PROJECT_PATH}:busybox-$(docker run --rm "${CI_PROJECT_PATH}:${BUILD_CACHE}" sh -c 'busybox | head -1 | cut -d " " -f 2')"

Build Container Image:
  extends: .docker_support:.publish_image
  stage: build
