#!/usr/bin/env sh
set -eua
here="$(dirname "${0}")"

SOURCE_BRANCH="${SOURCE_BRANCH:-$(2>/dev/null git rev-parse --abbrev-ref HEAD || true)}"
SOURCE_COMMIT="${SOURCE_COMMIT:-$(2>/dev/null git rev-parse --short HEAD || true)}"
COMMIT_MSG="${COMMIT_MSG:-Commit message}"
DOCKER_REPO="${DOCKER_REPO:-$(basename $(realpath "${here}"))}"
DOCKERFILE_PATH="${DOCKERFILE_PATH:-image/Dockerfile}"
DOCKER_TAG="${DOCKER_TAG:-latest}"
IMAGE_NAME="${IMAGE_NAME:-${DOCKER_REPO}:${DOCKER_TAG}}"

hooks="${here}/image/hooks"
for hook in post_checkout pre_build build post_build pre_test test post_test pre_push push post_push; do
  file="${hooks}/${hook}"
  if [ -x "${file}" ]; then
    "${file}"
  else
    >&2 echo "Ignoring missing hook ${hook}"
  fi
done
