#!/bin/sh
set -eu

TARGET_PLATFORMS='linux/amd64,linux/arm64,linux/arm/v7'

DOCKER_BUILDX_VERSION=v0.3.1
DOCKER_CLI_EXPERIMENTAL='enabled'
DOCKER_BUILD_COMMAND="docker buildx build --platform ${TARGET_PLATFORMS}"

apt-get install -q -y qemu-user-static
docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
wget "https://github.com/docker/buildx/releases/download/${DOCKER_BUILDX_VERSION}/buildx-${DOCKER_BUILDX_VERSION}.linux-amd64"
chmod +x "buildx-${DOCKER_BUILDX_VERSION}.linux-amd64"
cp "buildx-${DOCKER_BUILDX_VERSION}.linux-amd64" ~/.docker/cli-plugins/docker-buildx
docker buildx create --name builder --driver docker-container --use
